#!/bin/sh
# load-balance(N-WAN) Script VER 1.1i 2011.4.4 for openwrt  by QQ GROUP 120752328
. /lib/functions/network.sh
logpath=/tmp/nwan_log

uci_get() {
	uci -P /var/state get "$1" 2>/dev/null
}

uci_set_state (){

	uci -P /var/state set "$1" 2>/dev/null
}

uci_get_state (){

	uci -P /var/state get "$1" 2>/dev/null
}
get_wan_info (){
	#WAN_INTERFACE=$(echo ${INTERFACE} |grep -c -E "wan|vpn") #接口名字必须为wan或者vpn，否则无法自动更新路由
	#WAN_INTERFACE=$(echo ${INTERFACE} |grep -c wan) #20180830注释掉，接口中有了wan_6、wan1_6的接口
	WAN_INTERFACE=$(echo ${INTERFACE} |grep -v 6 |grep -c wan) #排除接口有“_6”的接口
	if [ "${WAN_INTERFACE}" -ge "1" ] ; then

		network_get_gateway gateway ${INTERFACE} true
		[ -z $gateway ] && exit 0
		network_get_ipaddrs ipaddr ${INTERFACE}
		[ -z $ipaddr ] && exit 0
		network_get_protocol proto ${INTERFACE}
	fi
}

cfg_enabled=$(uci_get_state nwan.@settings[0].enable)
[ "$cfg_enabled" = 1 ] || exit 0

logger -t nwan "Starting nwan due to $ACTION of $INTERFACE ($DEVICE)"
case "$ACTION" in
	ifup|ifupdate)
		echo ++ `date` +++${INTERFACE}+++${ACTION}++ >> $logpath
		echo "`date`++${INTERFACE} is up ">>/tmp/nwandebug
		get_wan_info
		echo "interface is available = ${WAN_INTERFACE}" >>/tmp/nwandebug
		if [ "${WAN_INTERFACE}" -ge "1" ] ; then
			uci -P /var/state revert nwan.${INTERFACE}
			uci -P /var/state revert network.${INTERFACE}.gateway
			uci_set_state nwan.${INTERFACE}=$INTERFACE
			uci_set_state nwan.${INTERFACE}.connect_time=$(sed -ne 's![^0-9].*$!!p' /proc/uptime)
			uci_set_state nwan.${INTERFACE}.device=$DEVICE
			uci_set_state nwan.${INTERFACE}.proto=$proto
			uci_set_state nwan.${INTERFACE}.ipaddr=$ipaddr
			uci_set_state nwan.${INTERFACE}.gateway=$gateway
			#uci_set_state nwan.${INTERFACE}.network=$new_network
			uci_set_state nwan.${INTERFACE}.status="1"
			#echo "WAN_INTERFACE=${WAN_INTERFACE}" >>/tmp/nwandebug
			#[ "${WAN_INTERFACE}" -ge "1" ] && sh /lib/nwan/route ifup_start $INTERFACE
			#telegram-send -g "✅${INTERFACE} is up ,addr=$ipaddr" &
			sh /root/scripts/sendtelegram.sh "✅*${INTERFACE}* is up ,*addr*=\`$ipaddr\`" &
			sh /lib/nwan/route ifup_start $INTERFACE

			# wan_name=$(echo ${INTERFACE} |grep -w wan2)
			# if [ "$wan_name" = "wan2" ] ; then
			#     sh /root/scripts/zerotier_moon.sh $ipaddr
			# fi
		fi
	 ;;
	ifdown)
		echo ++ `date` +++${INTERFACE}+++${ACTION}++ >> $logpath
		get_wan_info
		[ "${WAN_INTERFACE}" -ge "1" ] && sh /lib/nwan/route ifdown_start $INTERFACE
	;;
esac
