#!/bin/ash
# load-balance(N-WAN) Script VER 1.1i 2011.4.4 for openwrt  by QQ GROUP 120752328
. /lib/functions.sh
. /lib/functions/network.sh
logpath=/tmp/nwan_log
 
uci_get() {
	uci -P /var/state get "$1" 2>/dev/null
}

uci_set_state() {
	uci -P /var/state set "$1" 2>/dev/null
}

uci_get_state() {	
	uci -P /var/state get "$1" 2>/dev/null
}
load_nwan() {
	local name
	local enable
	local iface="$2"
	config_get enable $1 enable
	config_get name $1 name 
	[ "$name" = "$iface" ] && [ "$enable" = "1" ] && pass=1
}
get_wan_info() {
	#WAN_INTERFACE=$(echo ${INTERFACE} |grep -c -E "wan|vpn") #接口名字必须为wan或者vpn，否则无法自动更新路由
	#WAN_INTERFACE=$(echo ${INTERFACE} |grep -c wan)
	pass=0
	config_load nwan
	config_foreach load_nwan interface ${INTERFACE}
	#PROTO=$(echo $DEVICE | cut -d "-" -f1)
	#new_ipaddr=$(ifstatus ${INTERFACE} |awk '/"address"/{print $2}'|cut -d \" -f 2)
	#local new_netmask=$(uci_get_state  network.${INTERFACE}.netmask)
	#new_netmask=${new_netmask:-"255.255.255.0"}
	network_get_gateway gateway ${INTERFACE} true
	network_get_ipaddrs ipaddr ${INTERFACE}
	network_get_protocol proto ${INTERFACE}
	#new_gateway=$(ifstatus ${INTERFACE} |awk '/"nexthop"/{print $2}'|cut -d \" -f 2)
	#new_gateway=${new_gateway:-$(ifstatus ${INTERFACE} |awk '/"nexthop"/{print $2}'|cut -d \" -f 2)}
}

enabled=$(uci_get_state nwan.@settings[0].enable)
[ "$enabled" = 1 ] || exit 0
logger -t nwan "nwan works!"
case "$ACTION" in
	ifup)
		echo ++ `date` +++${INTERFACE}+++up++ >> $logpath
		get_wan_info
        echo "${INTERFACE}=$pass" >>/tmp/nwandebug
        if [ "$pass" -ge "1" ] ; then
            echo "wanup" >>/tmp/nwandebug
			uci -P /var/state revert nwan.${INTERFACE}
			uci -P /var/state revert network.${INTERFACE}.gateway
            uci_set_state nwan.${INTERFACE}=$INTERFACE 
            uci_set_state nwan.${INTERFACE}.connect_time=$(sed -ne 's![^0-9].*$!!p' /proc/uptime)
            uci_set_state nwan.${INTERFACE}.device=$DEVICE
            uci_set_state nwan.${INTERFACE}.proto=$proto
            uci_set_state nwan.${INTERFACE}.ipaddr=$ipaddr
            uci_set_state nwan.${INTERFACE}.gateway=$gateway
            #uci_set_state nwan.${INTERFACE}.network=$new_network
            uci_set_state nwan.${INTERFACE}.status="1"
            #echo "WAN_INTERFACE=$WAN_INTERFACE" >>/tmp/nwandebug
            #[ "$WAN_INTERFACE" -ge "1" ] && sh /lib/nwan/route ifup_start $INTERFACE 
            sh /lib/nwan/route ifup_start $INTERFACE 
        fi
	 ;;
	ifdown)
		echo ++ `date` +++${INTERFACE}+++down++ >> $logpath
		get_wan_info
		[ "$pass" -ge "1" ] && sh /lib/nwan/route ifdown_start $INTERFACE 
	;;
esac
