#!/bin/sh
uci -q batch <<-EOF >/dev/null
	delete ucitrack.@softethervpn[-1]
	add ucitrack softethervpn
	set ucitrack.@softethervpn[-1].init=softethervpn
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
