#!/bin/sh
#PROTO=$(echo $DEVICE | cut -d "-" -f1)
LOG='/tmp/smartroute.log'
enable=$(uci get smartroute.@smartroute[0].enable)
[ "$enable" = 1 ] || exit 0
iface=$(uci get smartroute.@smartroute[0].interface)
#oif=$(uci get network.${iface}.oif)
case "$ACTION" in
	ifup)
		if [ ${INTERFACE} == ${iface} ]; then
			echo \#\#$INTERFACE\#\# >>$LOG
			echo "up   $(date +"%Y-%m-%d#%T")" >>$LOG
			ip=`ifstatus ${INTERFACE} |awk '/"address"/{print $2}'|cut -d \" -f 2`
			echo "clientip:$ip" >>$LOG
			echo "$(date +%s)" >>$LOG
			logger -t smartroute "Running script due to $ACTION of $INTERFACE ($DEVICE)"
		
		/etc/init.d/smartroute start
		uci delete dhcp.@dnsmasq[0].server
		uci add_list dhcp.@dnsmasq[0].server='127.0.0.1#5353'
		uci commit
		/etc/init.d/dnsmasq restart
		#####绑定vpn到指定接口
		#####
		#oif=$(uci get network.${iface}.interface)
		#if [ ${INTERFACE} == ${oif} ]; then
			#ipsec restart
			#sleep 2
			#ipsec up l2tp-psk-client
		#fi
		fi
	 ;;
	ifdown)
		if [ ${INTERFACE} == ${iface} ]; then
			logger -t smartroute "Running script due to $ACTION of $INTERFACE"
			DWTime=$(date +%s)
			UPTime=$(tail -1 $LOG)
			sed -i '$d' $LOG #delete the last line of logfile
			DevTime=$(($DWTime - $UPTime))
			Duration=`awk 'BEGIN{printf "%.2f\n",'$DevTime'/60}'`
			echo "down $(date +"%Y-%m-%d#%T")" >>$LOG
			echo "Duration:$Duration minutes" >>$LOG
			echo "-------------------------------------" >>$LOG
			/etc/init.d/smartroute stop
			uci delete dhcp.@dnsmasq[0].server
			uci add_list dhcp.@dnsmasq[0].server='223.5.5.5'
			uci add_list dhcp.@dnsmasq[0].server='114.114.114.114'
			uci commit
			/etc/init.d/dnsmasq restart
		fi
	;;
esac
